# Generated by Django 4.2.1 on 2025-12-06 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcam_image', models.ImageField(upload_to='webcam_images/')),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcamuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.BinaryField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(upload_to='qrcodes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('grade_level', models.CharField(blank=True, choices=[('', 'Choose...'), ('1st Grade', '1st Grade'), ('2nd Grade', '2nd Grade'), ('3rd Grade', '3rd Grade'), ('4th Grade', '4th Grade'), ('5th Grade', '5th Grade'), ('6th Grade', '6th Grade'), ('7th Grade', '7th Grade'), ('8th Grade', '8th Grade'), ('9th Grade', '9th Grade'), ('10th Grade', '10th Grade'), ('11th Grade', '11th Grade'), ('12th Grade', '12th Grade'), ('Freshman - Univeristy', 'Freshman - Univeristy'), ('Sophmore - Univeristy', 'Sophmore - Univeristy'), ('Junior - Univeristy', 'Junior - Univeristy'), ('Senior - Univeristy', 'Senior - Univeristy'), ('Adult Learner', 'Adult Learner')], max_length=50)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('hometown', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('personal_website', models.URLField(blank=True)),
                ('personal_linkedin', models.URLField(blank=True)),
                ('p_color', models.CharField(default='#f8f9fa', max_length=255)),
                ('p_color_header', models.CharField(default='#000000', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_nft.jpg', upload_to='nft_images/')),
                ('image_ipfs_uri', models.CharField(default='', max_length=255)),
                ('contract_address', models.CharField(default='', max_length=42)),
                ('token_id', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
