# Generated by Django 4.2.1 on 2023-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos"),
        ),
        migrations.AddField(
            model_name="profile",
            name="company_website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mobile",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="office",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="personal_linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter",
            field=models.URLField(blank=True),
        ),
    ]
