# Generated by Django 4.2.2 on 2023-07-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_company_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="facebook",
            new_name="co_facebook",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="instagram",
            new_name="co_instagram",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="linkedin",
            new_name="co_linkedin",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="twitter",
            new_name="co_twitter",
        ),
        migrations.AddField(
            model_name="profile",
            name="co_city",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="co_state",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="co_street1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="co_street2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="co_zip",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
