# Generated by Django 4.2.2 on 2023-07-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_facebook_profile_co_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="co_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="profile",
            name="co_fax",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="co_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
