# Generated by Django 4.2.2 on 2023-07-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_co_email_profile_co_fax_profile_co_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="personal_facebook",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="personal_instagram",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="personal_twitter",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="personal_website",
            field=models.URLField(blank=True),
        ),
    ]
