# Generated by Django 4.2.1 on 2023-07-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_personal_facebook_profile_personal_instagram_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="company",
            new_name="comp",
        ),
    ]
