# Generated by Django 4.2.1 on 2023-07-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_nft"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="wallet_private_key",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
