# Generated by Django 4.2.1 on 2023-07-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_profile_wallet_private_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="wallet_private_key",
        ),
    ]
