# Generated by Django 4.2.1 on 2023-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_nft_image_alter_nft_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="image",
            field=models.ImageField(default="default_nft.jpg", upload_to="nft_images/"),
        ),
    ]
