# Generated by Django 4.2.1 on 2023-08-01 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0013_alter_nft_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nft",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
