# Generated by Django 4.2.1 on 2023-08-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_nft_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
    ]
