# Generated by Django 4.2.1 on 2023-08-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="private_key",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_address",
            field=models.CharField(max_length=100),
        ),
    ]
