# Generated by Django 4.2.1 on 2023-08-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_wallet_private_key_alter_wallet_wallet_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="contract_address",
            field=models.CharField(default="", max_length=42),
        ),
        migrations.AddField(
            model_name="nft",
            name="image_ipfs_uri",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="nft",
            name="token_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="nft",
            name="wallet_address",
            field=models.CharField(default="", max_length=42),
        ),
    ]
