# Generated by Django 4.2.1 on 2023-08-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_nft_contract_address_nft_image_ipfs_uri_nft_token_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="private_key",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_address",
            field=models.CharField(default="", max_length=100),
        ),
    ]
