# Generated by Django 4.2.1 on 2023-08-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_wallet_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_company_color",
            field=models.CharField(default="#f8f9fa", max_length=7),
        ),
    ]
