# Generated by Django 4.2.1 on 2023-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_profile_preferred_company_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="last_updated_timestamp",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="nft",
            name="private_key",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_personal_color",
            field=models.CharField(default="#f8f9fa", max_length=7),
        ),
    ]
