# Generated by Django 4.2.1 on 2023-08-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_remove_nft_last_updated_timestamp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="private_key",
            new_name="private_key_user",
        ),
    ]
