# Generated by Django 4.2.1 on 2023-08-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_rename_private_key_wallet_private_key_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="preferred_personal_color",
            new_name="p_color",
        ),
    ]
