# Generated by Django 4.2.1 on 2023-08-13 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0025_rename_preferred_personal_color_profile_p_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp", models.CharField(blank=True, max_length=200)),
                ("company_website", models.URLField(blank=True)),
                (
                    "company_logo",
                    models.ImageField(
                        default="default_co.jpg", upload_to="company_logos"
                    ),
                ),
                ("co_street1", models.CharField(blank=True, max_length=200)),
                ("co_street2", models.CharField(blank=True, max_length=200)),
                ("co_city", models.CharField(blank=True, max_length=200)),
                ("co_state", models.CharField(blank=True, max_length=200)),
                ("co_zip", models.CharField(blank=True, max_length=5)),
                ("co_phone", models.CharField(blank=True, max_length=20)),
                ("co_email", models.EmailField(blank=True, max_length=254)),
                ("co_fax", models.CharField(blank=True, max_length=20)),
                ("co_twitter", models.URLField(blank=True)),
                ("co_facebook", models.URLField(blank=True)),
                ("co_linkedin", models.URLField(blank=True)),
                ("co_instagram", models.URLField(blank=True)),
                (
                    "preferred_company_color",
                    models.CharField(default="#f8f9fa", max_length=7),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("office", models.CharField(blank=True, max_length=20)),
                ("personal_website", models.URLField(blank=True)),
                ("personal_twitter", models.URLField(blank=True)),
                ("personal_facebook", models.URLField(blank=True)),
                ("personal_linkedin", models.URLField(blank=True)),
                ("personal_instagram", models.URLField(blank=True)),
                ("p_color", models.CharField(default="#f8f9fa", max_length=7)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
