# Generated by Django 4.2.1 on 2023-08-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_companyprofile_personalprofile_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalprofile",
            name="office",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
