# Generated by Django 4.2.1 on 2023-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_personalprofile_p_color_header"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyprofile",
            old_name="preferred_company_color",
            new_name="c_color",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="c_color_header",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
