# Generated by Django 4.2.1 on 2023-08-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0029_rename_preferred_company_color_companyprofile_c_color_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="company_logo_ipfs_uri",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
