# Generated by Django 4.2.1 on 2023-09-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_emailsignature"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailSignature",
        ),
    ]
