# Generated by Django 4.2.1 on 2023-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_qrscanevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrscanevent",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="qrscanevent",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
