# Generated by Django 4.2.1 on 2023-09-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_qrscanevent_city_qrscanevent_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrscanevent",
            name="tx_hash",
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
