# Generated by Django 4.2.1 on 2023-09-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_alter_personalprofile_p_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalprofile",
            name="p_color",
            field=models.CharField(
                default="linear-gradient(145deg, #f3f4f6, #d1d2d4)", max_length=255
            ),
        ),
    ]
