# Generated by Django 4.2.1 on 2023-09-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_alter_personalprofile_p_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrscanevent",
            name="scan_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
