# Generated by Django 4.2.1 on 2023-09-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_alter_qrscanevent_scan_timestamp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyProfile",
        ),
    ]
