# Generated by Django 4.2.1 on 2023-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0044_delete_companyprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalprofile",
            name="office",
        ),
        migrations.RemoveField(
            model_name="personalprofile",
            name="personal_facebook",
        ),
        migrations.RemoveField(
            model_name="personalprofile",
            name="personal_instagram",
        ),
        migrations.RemoveField(
            model_name="personalprofile",
            name="personal_twitter",
        ),
        migrations.RemoveField(
            model_name="personalprofile",
            name="title",
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="grade_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Choose..."),
                    ("1", "1st Grade"),
                    ("2", "2nd Grade"),
                    ("3", "3rd Grade"),
                    ("4", "4th Grade"),
                    ("5", "5th Grade"),
                    ("6", "6th Grade"),
                    ("7", "7th Grade"),
                    ("8", "8th Grade"),
                    ("9", "9th Grade"),
                    ("10", "10th Grade"),
                    ("11", "11th Grade"),
                    ("12", "12th Grade"),
                    ("13", "Freshman - Univeristy"),
                    ("14", "Sophmore - Univeristy"),
                    ("15", "Junior - Univeristy"),
                    ("17", "Senior - Univeristy"),
                    ("Adult", "Adult Learner"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="hometown",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="personalprofile",
            name="school",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
