# Generated by Django 4.2.1 on 2023-09-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0003_upvoteevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="num_vote_down",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="num_vote_up",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="vote_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
