# Generated by Django 4.2.1 on 2023-09-19 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("socialmedia", "0005_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_cost",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="is_tokengated_content",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="subject",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="visible_to",
            field=models.ManyToManyField(
                related_name="paid_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
