# Generated by Django 4.2.1 on 2023-09-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0007_userdebt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
