# Generated by Django 4.2.1 on 2023-09-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0008_delete_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="files",
            field=models.FileField(blank=True, null=True, upload_to="post_files/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=2000),
        ),
    ]
