# Generated by Django 4.2.1 on 2023-09-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0009_post_files_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content_cost",
            field=models.IntegerField(default=0),
        ),
    ]
