# Generated by Django 4.2.1 on 2023-09-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0010_alter_post_content_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content_cost",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
