# Generated by Django 4.2.1 on 2023-09-21 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("socialmedia", "0014_post_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="num_vote_down",
        ),
        migrations.RemoveField(
            model_name="post",
            name="num_vote_up",
        ),
        migrations.RemoveField(
            model_name="post",
            name="upvotes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="vote_score",
        ),
        migrations.RemoveField(
            model_name="upvoteevent",
            name="post",
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote_score", models.IntegerField(db_index=True, default=0)),
                ("num_vote_up", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "num_vote_down",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="replies/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="replies/videos/"
                    ),
                ),
                (
                    "files",
                    models.FileField(blank=True, null=True, upload_to="replies/files/"),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="socialmedia.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="upvoteevent",
            name="reply",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upvotes",
                to="socialmedia.reply",
            ),
        ),
    ]
