# Generated by Django 4.2.1 on 2023-09-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "socialmedia",
            "0015_remove_post_created_at_remove_post_num_vote_down_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="upvoteevent",
            name="reply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upvotes",
                to="socialmedia.reply",
            ),
        ),
    ]
