# Generated by Django 4.2.1 on 2023-09-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0018_unit_post_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="unit",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="socialmedia.unit",
            ),
            preserve_default=False,
        ),
    ]
