# Generated by Django 4.2.1 on 2023-09-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0019_alter_post_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(
                choices=[
                    ("unit1", "Unit 1: Dreams for the Future?"),
                    ("unit2", "Unit 2: Feelings in My Money Matters Group"),
                    ("unit3", "Unit 3: Prioritize Spending"),
                    ("unit4", "Unit 4: Budgeting to Reach My Goals"),
                    ("unit5", "Unit 5: Saving to Reach My Goals"),
                    ("unit6", "Unit 6: Understanding Why I Spend Money"),
                    ("unit7", "Unit 7: Managing My Debt"),
                    ("unit8", "Unit 8: Protecting My Identity"),
                    ("unit9", "Unit 9: Helping Other Teens Reach Their Goals"),
                ],
                max_length=200,
            ),
        ),
    ]
