# Generated by Django 4.2.1 on 2023-09-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0020_alter_unit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reply",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
