# Generated by Django 4.2.1 on 2023-09-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0021_post_is_approved_reply_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
